// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PiecesCandyCo.DataAccess.Data;

#nullable disable

namespace PiecesCandyCo.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231104232804_addProductsToDb")]
    partial class addProductsToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PiecesCandyCo.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            DisplayOrder = 1,
                            Name = "Chocolate"
                        },
                        new
                        {
                            Id = 102,
                            DisplayOrder = 3,
                            Name = "Hard Candy"
                        },
                        new
                        {
                            Id = 103,
                            DisplayOrder = 2,
                            Name = "Gummies"
                        },
                        new
                        {
                            Id = 107,
                            DisplayOrder = 4,
                            Name = "Special Edition"
                        });
                });

            modelBuilder.Entity("PiecesCandyCo.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price10")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 301,
                            Description = "Perfect for any occasion, these gummy bears come infused with flavors of champagne.",
                            Name = "Champagne Gummy Bears (12 PK)",
                            Price = 10.949999999999999,
                            Price10 = 8.9499999999999993
                        },
                        new
                        {
                            Id = 302,
                            Description = "Perfect for any occasion, these gummy bears come infused with flavors of rosé wine.",
                            Name = "Rosé Gummy Bears (12 PK)",
                            Price = 10.949999999999999,
                            Price10 = 8.9499999999999993
                        },
                        new
                        {
                            Id = 303,
                            Description = "Perfect for any occasion, this chocolate bar is topped with peppermint and marshmallows.",
                            Name = "Winter Wonderland White Chocolate Bar",
                            Price = 14.949999999999999,
                            Price10 = 12.949999999999999
                        },
                        new
                        {
                            Id = 304,
                            Description = "Perfect for any occasion, this chocolate bar is filled with liquid cappuccino.",
                            Name = "Cappuccino Chocolate Bar",
                            Price = 14.949999999999999,
                            Price10 = 12.949999999999999
                        },
                        new
                        {
                            Id = 305,
                            Description = "Perfect for any occasion, these candies come infused with flavors of whiskey.",
                            Name = "Whiskey Sour Hard Candies (12 PK)",
                            Price = 10.949999999999999,
                            Price10 = 8.9499999999999993
                        },
                        new
                        {
                            Id = 306,
                            Description = "Perfect for any occasion, these candies come in pineapple flavor.",
                            Name = "Pineapple Candy (12 PK)",
                            Price = 10.949999999999999,
                            Price10 = 8.9499999999999993
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
